### ISSUE TITLE
Convenience method to get the latest model for a given model type

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-nagl-models#12]
## Is your feature request related to a problem? ##

As a user, it would be great if there was a method I could use to grab the latest released model (eventually with the option to choose a "production" model once one is released) for a given model type. 

Note: I say model type here because I assume by the "am1bcc" tag in the model that other charge models might come along some point.

## Describe the solution you'd like ##

Maybe some kind of method with a signature like this:

```
def get_latest_model(model_type: str = 'am1bcc', production_only: bool = True) -> str
```

## Describe alternatives you've considered ##

Relying on the `list_available_models` sort - assuming there are no other model types and it's guaranteed to be release ordered.

**Comment by lilyminium** [comment]
> As a user, it would be great if there was a method I could use to grab the latest released model (eventually with the option to choose a "production" model once one is released) for a given model type.

I'm happy to do this but it does runs a bit counter to the philosophy we have in `openff-forcefields`, where we require users to specify which force field they're after every time. The main worry I would have here is that users would suddenly start getting different charges with the same script if a new model is released and picked up instead. Is needing to specify the model problematic in your workflow?

**Comment by IAlibay** [comment]
Yes, it would be useful for us to be able to identify the latest release of a model. If anything, for validation purposes being able to programmatically tell that a model is out of date helps.

We can deal with this on our end by parsing the strings but we would need to know that the model names have an agreed upon format that will not be changing going forward.

**Comment by IAlibay** [comment]
I don't think I actually answered the question re users & being problematic for our workflow: it's hard to tell right now, part of the issue is that we don't have a good idea of how quickly these models will be released.

That being said the main uses of all this, for now, isn't so much user facing but developer facing. There are lots of cases where an ordered list would help (documentation comes to mind as another use case).

**Comment by lilyminium** [comment]
Thanks for the info about what you need this for. I went back and forth on this and did eventually open PR #13, but I wonder if most of these problems could just be solved with better documentation (e.g. an ongoing table of models like https://github.com/openforcefield/openff-forcefields#how-to-cite)? I don't anticipate that these models will be released too often, although we do anticipate new models coming along with different charge methods / property predictions.

**Comment by IAlibay** [comment]
I've added my thoughts in the PR on maybe a better way to avoid some of the concerns.

However I do agree that better documentation here would go a long way, we definitely would prefer to avoid having our own documentation of available charge methods. Additionally, if the model names have documented guaranteed patterns then we can always just have our own filters downstream.
