### ISSUE TITLE
Add `get_models_by_type` to `__init__.py`?

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-nagl-models#16]
## Is your feature request related to a problem? ##

Most other utility methods are available at top level import but `get_models_by_type` isn't.

Would it make sense to have it as a top level import?

## Describe the solution you'd like ##

Add `get_models_by_type` to the top level `__init__.py`.

## Describe alternatives you've considered ##

Carry on importing from `openff.nagl_models.openff_nagl_models`.

**Comment by lilyminium** [comment]
Sure, sounds good to me -- updated!
